sudo: required

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2
- while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &

script:
- bash init.sh
- docker build -t wise2c/playbook:$TRAVIS_BRANCH .
- docker tag wise2c/playbook:$TRAVIS_BRANCH wise2c/playbook:v1.16.3

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wise2c/playbook:$TRAVIS_BRANCH && docker push wise2c/playbook:v1.16.3
  on:
    all_branches: true
#    condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
