sudo: required

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2
- docker pull wise2ck8s/kube-version:v1.12

script:
- bash init.sh
- docker build -t wise2c/playbook:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wise2c/playbook:$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
