version: '2'
services:
  deploy:
    container_name: deploy-main
    image: wise2ck8s/pagoda:v1.0
    restart: always
    entrypoint: sh
    command:
    - -c
    - "/root/pagoda -logtostderr -v 4 -w /workspace"
    ports:
    - 88:80
    - 8088:8080
    volumes:
    - /root/.ssh:/root/.ssh
    - $PWD/deploy:/deploy
    volumes_from:
    - playbook
  ui:
    container_name: deploy-ui
    image: wise2ck8s/deploy-ui:v1.1
    restart: always
    network_mode: "service:deploy"
  playbook:
    container_name: deploy-playbook
    image: wise2ck8s/playbook:v1.11.4
    volumes:
    - playbook:/workspace
  yum-repo:
    container_name: deploy-yumrepo
    image: wise2ck8s/yum-repo:v1.11.4
    ports:
    - 2009:2009 
    restart: always
volumes:
  playbook:
    external: false
