version: '2'
services:
  deploy:
    container_name: deploy-main
    image: wise2c/pagoda:v1.2.0
    restart: always
    entrypoint: sh
    command:
    - -c
    - "/root/pagoda -logtostderr -v 4 -w /workspace"
    ports:
    - 88:80
    - 8088:8080
    volumes:
    - $HOME/.ssh:/root/.ssh
    - $PWD/deploy:/deploy
    volumes_from:
    - playbook
  ui:
    container_name: deploy-ui
    image: wise2c/deploy-ui:v1.8
    restart: always
    network_mode: "service:deploy"
  playbook:
    container_name: deploy-playbook
    image: wise2c/playbook:v1.18.6
    volumes:
    - playbook:/workspace
  yum-repo:
    container_name: deploy-yumrepo
    image: wise2c/yum-repo:v1.18.6
    ports:
    - 2009:2009 
    restart: always
volumes:
  playbook:
    external: false
