endpoint: {{ if eq (print .Property.endpoint) "" -}}
          {{ (index .Hosts.self 0).IP }}
          {{- else -}}
          {{ .Property.endpoint }}
          {{- end }}
https: false
user: admin
password: {{ if eq (print .Property.password) "" -}}
          Harbor12345
          {{- else -}}
          {{ .Property.password }}
          {{- end }}
